version: "3.8"

services:
  postgresql:
    image: postgres:12-alpine
    container_name: api_postgresql
    ports:
      - "${DB_PORT}:5432"
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - web_api

  api:
    build: .
    container_name: api_server
    ports:
      - "${API_PORT}:8080"
    restart: always
    networks:
      - web_api

volumes:
  postgresql_data:

networks:
  web_api:
    driver: bridge